security:
  oauth2:
    client:
      scope: read,write
      auto-approve-scopes: '.*'

github:
  client:
    clientId: 1adba012f87f1b853615
    clientSecret: 6a15a03b62d5a8cf51a27c7be7af0172b587f033
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    scope: repo
  resource:
    userInfoUri: https://api.github.com/user

contracts:
  url: https://api.github.com/repos/barreld/contracts/contents
